### ISSUE TITLE
run_Conv_KCF in benchmark error

### ISSUE THREAD

**Issue by ninizhang** [lidongxuan/Conv-KCF#2]
hello
I am really interested in your work. while when I run the code in benchmark,there is error.
Need I modify the run_Conv_KCF or just run it?
thank you

**Comment by lidongxuan** [comment]
I think you should know how to use OTB first. run_Conv_KCF.m file is used to run the benchmark. If you just want to visualize tracking process with a bounding box, you only need to run rundemo.m.

**Comment by ninizhang** [comment]
thank you for your advice.  it is helpful.
